# 라이브러리 설치

In [1]:
!pip install numpy

In [2]:
import numpy as np

print(np.__version__)

2.1.1


In [5]:
#help(np) #잘 모르면 써먹자

In [7]:
num1 = [1, 2, 3]
num2 = [4, 5, 6]

num1 + num2 #원하던 결과값: [5, 7, 9]

[1, 2, 3, 4, 5, 6]

In [9]:
import numpy as np

num1 = np.array([1, 2, 3])
num2 = np.array([4, 5, 6])

result = num1 + num2
print(result)

[5 7 9]


In [25]:
num1_arr = np.array([1, 2, 3])

In [26]:
num1_arr.T

array([1, 2, 3])

In [27]:
num1_arr.max()

np.int64(3)

In [28]:
import numpy as np

# 1차원 배열 생성
arr1 = np.array([1, 2, 3])

# 2차원 배열 생성
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# 출력
print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


# 배열 만드는 방법

In [29]:
# 기본적으로 다른 데이터 자료형으로 numpy 배열로 변환
# 배열 생성
print(np.ones(3))

[1. 1. 1.]


# 배열의 차원을 변경

In [33]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [34]:
print(arr2.ndim)

2


In [35]:
print(arr2.shape)

(2, 3)


In [38]:
print(arr1.shape)

(3,)


In [40]:
print(arr2.size)

6


In [41]:
print(arr1.size)

3


In [43]:
print(arr2.dtype)

int64


In [64]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# 배열의 덧셈
sum_arr = arr1 + arr2  # [5, 7, 9]

# 배열의 곱셈
prod_arr = arr1 * arr2  # [4, 10, 18]

# 배열의 나눗셈
div_arr = arr2 / arr1  # [4.0, 2.5, 2.0]

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 배열 전체의 합계
sum_arr = np.sum(arr)  # 21

# 배열의 각 열에 대한 합계
col_sum = np.sum(arr, axis=0)  # [5, 7, 9]

# 배열의 평균
mean_arr = np.mean(arr)  # 3.5

# 배열의 표준 편차
std_arr = np.std(arr)  # 1.707825127659933

In [42]:
a16 = np.array([1.333333], dtype = np.float16)
a32 = np.array([1.333333], dtype = np.float32)

print(a16)
print(a32)

[1.333]
[1.333333]


In [44]:
arr = np.array([-1, 2, -3])
arr/0

C:\Users\dndtn\AppData\Local\Temp\ipykernel_18448\3465403327.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([-inf,  inf, -inf])

## 결측치
- Missing Values : 잃어버린 값
- nan : Not a Number --> 아직 정의되지 않은 숫자 의미

In [49]:
print(np.nan, type(np.nan))

nan <class 'float'>


In [50]:
print(np.nan, type(np.inf))

nan <class 'float'>


In [65]:
# 인덱싱 & 슬라이싱

In [67]:
arr = np.arange(10)
arr[1:5]

array([1, 2, 3, 4])

In [69]:
arr = np.arange(10).reshape(2,5)
arr[0][1]

np.int64(1)

In [70]:
arr = np.arange(10000).reshape(100,100)
arr[0:4][0:1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [82]:
arr = np.arange(20).reshape(4, 5)
arr[7:, 6:]

array([], shape=(0, 0), dtype=int64)

In [83]:
import numpy as np

# 100x100 배열 생성
arr = np.arange(10000).reshape(100, 100)

# 필요한 값만 슬라이싱
result = arr[0, 7:16]
print(result)

[ 7  8  9 10 11 12 13 14 15]


## 브로드캐스팅 연산

In [85]:
a = np.array([1, 2, 3])
b = 3.0
a + b

array([4., 5., 6.])

In [121]:
import numpy as np

arr = np.arange(25).reshape(5,5)

In [114]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [118]:
import numpy as np

arr1 = np.arange(9).reshape(3, 3)

In [122]:
arr = np.zeros((3,3))

In [130]:
arr = np.arange(16).reshape(4,4)
arr[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

## 조건 연산
- 원하는 결과값: True/False

In [133]:
arr = np.array([10, 20, 30])
arr > 10

array([False,  True,  True])

In [137]:
arr = np.array([10, 20, 30])
cond = [False,  True,  True]

arr[cond]

array([20, 30])

In [138]:
arr = np.array([18, 20, 50, 30, 16])
cond = arr > 18

arr[cond]

array([20, 50, 30])

In [148]:
arr = np.array([18, 20, 50, 30, 16, 65, 70])
cond0 = arr > 18
cond1 = arr < 65

arr[cond0 & cond1]

array([20, 50, 30])

In [147]:
arr[cond0 |cond1]

array([18, 20, 50, 30, 16, 65, 70])

In [149]:
# 권장사항, 이유: pandas 다중조건 필터링할 때는 아래방법으로만 가능
arr[(cond0 |cond1)]

array([18, 20, 50, 30, 16, 65, 70])

In [151]:
np.where(a < 5, a, 10*a)

array([1, 2, 3])

## 함수와 메서드

In [152]:
arr = np.arange(8).reshape(4, 2)
arr.sum()

np.int64(28)

In [153]:
arr.sum(axis = 0)

array([12, 16])

In [154]:
arr.sum(axis = 1)

array([ 1,  5,  9, 13])

In [165]:
# 랜덤 함수 만들기
np.random.randint(10)

4

In [162]:
np.random.seed(42) # 머신러닝에서 자주 씀
np.random.randint(10)

6

In [166]:
np.random.randint(46, size = 6)

array([38, 18, 22, 10, 10, 23], dtype=int32)

In [167]:
np.random.randint(46, size = (3,4))

array([[35, 39, 23,  2],
       [21,  1, 23, 43],
       [29, 37,  1, 20]], dtype=int32)

In [170]:
x = np.linspace(0, 100, 11)
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
